image: registry.gitlab.com/floweethehub/buildenvironments/builder-debian:stable

stages:
- build
- test
- deploy

variables:
  HUB_IMG: flowee/hub:${CI_COMMIT_REF_NAME}

#####  Debian stable

build-debian-stable:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -Dbuild_tests=true -Denable_wallet=true -DCMAKE_BUILD_TYPE=ReleaseWithDebugInfo -DCMAKE_INSTALL_PREFIX=.. ..
    - echo nproc=`nproc`
    - make univalue
    - make -j0`nproc` install
  artifacts:
    paths:
    - bin
    - build/testing/test/test_hub
    - build/testing/utxo/test_utxo
    expire_in: 1 hrs

# this fails on gitlab but the same setup passes on my laptop.
# Best idea I have is that its a memory thing. Disable for now.
.test_hub.deb:
  stage: test
  script: testing/test-parallel build/testing/test/test_hub
  dependencies:
  - build-debian-stable

test_utxo.deb:
  stage: test
  script: testing/test-parallel build/testing/utxo/test_utxo
  dependencies:
  - build-debian-stable

#####  Static build (Linux)

build-static:
  image: registry.gitlab.com/floweethehub/buildenvironments/builder-static:stable
  stage: build
  script: build_static
  artifacts:
    paths:
    - bin
    - etc/flowee
    expire_in: 1 hrs

# how to create a .deb file TODO
# https://about.gitlab.com/2016/10/12/automated-debian-package-build-with-gitlab-ci/

flowee-the-hub-linux.zip:
  stage: deploy
  script: for i in bin/*; do strip $i; done
  artifacts:
    name: flowee-the-hub-${CI_COMMIT_SHA}
    paths:
    - bin
    - etc
  dependencies:
  - build-static
  only: [master]

createHubDocker:
  stage: deploy
  script:
    - docker login -u flowee -p $DOCKER_TOKEN
    - mv bin support/docker/hub
    - docker build --tag=$HUB_IMG support/docker/hub
    - docker image push $HUB_IMG
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build-static
  only:
    - branches@gitlab-org/FloweeTheHub
  allow_failure: true

##### Build as standard as it gets.

build-debian-nowallet:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -Denable_gui=false ..
    - make univalue
    - make -j0`nproc` all

